### ISSUE TITLE
如何导入robot_interface包（v3.8.4 Aliengo SDK）

### ISSUE THREAD

**Issue by kongshanpai01** [unitreerobotics/unitree_legged_sdk#145]
v3.8.4 Aliengo SDK编译完成后运行python的example文件（如example_walk.py），显示报错：
Traceback (most recent call last):
  File "/home/kongshan-pai/unitree_legged_sdk-3.8.4/example_py/example_walk.py", line 11, in <module>
    import robot_interface as sdk
ImportError: libunitree_legged_sdk.so: cannot open shared object file: No such file or directory

似乎是libunitree_legged_sdk.so文件格式或路径的问题？请问应当如何配置

**Comment by AlexLiu-bit** [comment]
请问您解决这个问题了吗 @kongshanpai01 

> v3.8.4 Aliengo SDK编译完成后运行python的example文件（如example_walk.py），显示报错： Traceback (most  #recent call last): File "/home/kongshan-pai/unitree_legged_sdk-3.8.4/example_py/example_walk.py", line 11, in import robot_interface as sdk ImportError: libunitree_legged_sdk.so: cannot open shared object file: No such file or directory
> 
> 似乎是libunitree_legged_sdk.so文件格式或路径的问题？请问应当如何配置

**Comment by TommyZihao** [comment]
同问
